025-06-14 12:52:51,050 [WARNING] D:\code\anaconda3\Lib\site-packages\paramiko\pkey.py:82: CryptographyDeprecationWarning:

TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.


2025-06-14 12:52:51,069 [WARNING] D:\code\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning:

Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.


2025-06-14 12:52:51,069 [WARNING] D:\code\anaconda3\Lib\site-packages\paramiko\transport.py:243: CryptographyDeprecationWarning:

TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.


2025-06-14 12:52:51,378 [INFO] 开始处理视频: 1.mkv
2025-06-14 12:52:51,378 [INFO] 使用模型: faster-base
2025-06-14 12:52:51,378 [INFO] 运行设备: cuda
2025-06-14 12:52:52,744 [INFO] CUDA版本: 12.1
2025-06-14 12:52:52,744 [INFO] GPU: NVIDIA GeForce RTX 3060 Laptop GPU
2025-06-14 12:52:52,744 [INFO] GPU显存: 6.00 GB
2025-06-14 12:52:52,744 [ERROR] 处理过程中发生错误: 不支持的模型: faster-base。支持的模型: tiny, base, small, medium, large, faster-base, faster-large, firered-aed, firered-llm
Traceback (most recent call last):
  File "D:\Desktop\test-main\main.py", line 526, in main
    extractor = VideoSubtitleExtractor(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\test-main\main.py", line 389, in __init__
    self.model_wrapper = ModelFactory.create_model(model_id, device=self.device, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\test-main\main.py", line 375, in create_model
    raise ValueError(f"不支持的模型: {model_id}。支持的模型: tiny, base, small, medium, large, faster-base, faster-large, firered-aed, firered-llm")
ValueError: 不支持的模型: faster-base。支持的模型: tiny, base, small, medium, large, faster-base, faster-large, firered-aed, firered-llm
Traceback (most recent call last):
  File "D:\Desktop\test-main\main.py", line 567, in <module>
    main()
  File "D:\Desktop\test-main\main.py", line 564, in main
    extractor.cleanup()
    ^^^^^^^^^
UnboundLocalError: cannot access local variable 'extractor' where it is not associated with a value
